# The contents of this file is based on https://github.com/home-assistant/core/blob/dev/pyproject.toml

target-version = "py313"

[lint]
select = [
    "ALL",
]

ignore = [
    "ANN401", # Dynamically typed expressions (typing.Any) are disallowed
    "D203", # no-blank-line-before-class (incompatible with formatter)
    "D212", # multi-line-summary-first-line (incompatible with formatter)
    "COM812", # incompatible with formatter
    "ISC001", # incompatible with formatter
]

[lint.per-file-ignores]
"tests/**/*.py" = [
    "S101",    # Use of assert detected (expected in tests)
    "ARG001",  # Unused function argument (fixtures)
    "ANN201",  # Missing return type annotation for public function
    "ANN202",  # Missing return type annotation for private function
    "TC002",   # Move third-party import into type-checking block
    "TC003",   # Move stdlib import into type-checking block
    "PLC0415", # Import should be at top-level of file
    "D103",    # Missing docstring in public function
    "SLF001",  # Private member accessed (testing internals)
    "PLR0913", # Too many arguments in function definition
    "FBT001",  # Boolean-typed positional argument
    "FBT002",  # Boolean default positional argument
]

[lint.flake8-pytest-style]
fixture-parentheses = false

[lint.pyupgrade]
keep-runtime-typing = true

[lint.mccabe]
max-complexity = 25
